---
title: "Data filtering & prevalence-based performance standards"
output: html_document
date: "2026-02-08"
---

```{r setup, include=FALSE}
rm(list = ls())
library(anytime)
library(tidyverse)
library(dplyr)
library(openxlsx)
library(emmeans)
library(lme4)
library(ggplot2)
library(scales)
library(patchwork)
library(splines)

```

```{r loading raw data & cleaning}
## pull up data files
fy23 <- read.csv("../Raw data/fy23.csv", header=TRUE)
fy24 <- read.csv("../Raw data/fy24.csv", header=TRUE)
fy25 <- read.csv("../Raw data/fy25.csv", header=TRUE)

## combine data files into one "data" dataframe
data <- rbind(fy23, fy24)
data <- rbind(data, fy25)

##convert dates to YYYY-MM-DD format
##select data from 2023-01-01 to 2025-09-30 (24-month timeframe)
data$collection_date <- anydate(data$collection_date)
data <- subset(data, data$collection_date > "2022-12-31" & data$collection_date < "2025-10-01")

##select data from chicken parts project only
data <- subset(data, data$project_code == "HC_CPT_LBW01")

## exclude samples with no data result
data <- subset(data, data$salmonella_sp_analysis!="NULL")

## exclude product_type==NULL
data <- subset(data, data$product_type!="NULL")

## exclude samples from pilot plant establishments
data <- subset(data, data$establishment_number!="P20604+V20604")
data <- subset(data, data$establishment_number!="P1201")
data <- subset(data, data$establishment_number!="P1304B+V1304B")
data <- subset(data, data$establishment_number!="P1304A+V1304A")

##save all the establishment IDs in a separate vector
establishment_ids <- sort(unique(data$establishment_id))

##pull up MPI directory csv
establishment_size_data<-read.csv("../Raw data/MPI_Directory_by_Establishment_Number.csv", header=TRUE)

##select for establishments that are present in our establishment_ids vector
establishment_size_data<-filter(establishment_size_data, establishment_size_data$establishment_id %in% data$establishment_id)

##grab establishment information
data$establishment_size=NA
data$establishment_zip=NA
data$latitude=NA
data$longitude=NA

for (i in 1:length(establishment_ids)) {
  row = establishment_size_data[which(establishment_size_data$establishment_id==establishment_ids[i], arr.ind=TRUE)[1],]
  data$establishment_size[data$establishment_id==establishment_ids[i]]<-row$size
  data$establishment_zip[data$establishment_id==establishment_ids[i]]<-row$zip
  data$latitude[data$establishment_id==establishment_ids[i]]<-row$latitude
  data$longitude[data$establishment_id==establishment_ids[i]]<-row$longitude
}

#exclude samples without establishment size information
data<-subset(data, !is.na(data$establishment_size))
data<-subset(data, data$establishment_size!="N / A")

##change screening result of Negative samples with an enumeration value to "Positive"
data$salmonella_sp_analysis[data$salmonella_sp_analysis=="Negative" & data$salmonella_quantitative_cfu_ml=="<10"]<-"Positive"

data<-select(data, form_id, establishment_id, establishment_number, establishment_name, establishment_size, establishment_state, project_code, collection_date, sample_source_name, product_type, salmonella_sp_analysis, salmonella_quantitative_cfu_ml, establishment_zip, latitude, longitude)

##convert all the "NULL"s to NA (R can intrinsically recognize NA)
data$salmonella_quantitative_cfu_ml[which(data$salmonella_quantitative_cfu_ml == "NULL")] <- NA

write.csv(data, "data_prevalence.csv")


##read in serotypes data files
fy23_serotypes <- read.csv("../Raw data/fy23 serotypes.csv", header=TRUE)
fy24_serotypes <- read.csv("../Raw data/fy24 serotypes.csv", header=TRUE)
fy25_serotypes <- read.csv("../Raw data/fy25 serotypes.csv", header=TRUE)

## combine serotype data files into one "serotypes" dataframe
serotypes <- rbind(fy23_serotypes, fy24_serotypes)
serotypes <- rbind(serotypes, fy25_serotypes)

##pull form ids (sample ids)
salmonella_positive_ids <- data %>%
  filter(salmonella_sp_analysis == "Positive") %>%
  pull(form_id)

##subset salmonella data
serotypes_matched <- serotypes %>%
  filter(grepl("SALM", pathogen_number)) %>%
  filter(form_id %in% salmonella_positive_ids)

unique_form_id<-unique(serotypes_matched$form_id)

serotypes_wide <- serotypes_matched %>%
  group_by(form_id) %>%
  mutate(isolate_n = row_number()) %>%
  filter(isolate_n <= 2) %>%
  pivot_wider(
    id_cols = form_id,
    names_from = isolate_n,
    values_from = salmonella_serotype,
    names_prefix = "salmonella_serotype"
  )

#join to data
data_serotype <- data %>%
  mutate(form_id = trimws(as.character(form_id))) %>%
  left_join(
    serotypes_wide %>%
      mutate(form_id = trimws(as.character(form_id))) %>%
      select(form_id, salmonella_serotype1),
    by = "form_id"
  ) %>%
  mutate(
    salmonella_serotype1 = case_when(
      salmonella_sp_analysis == "Positive" & is.na(salmonella_serotype1) ~ "No serotype data available",
      salmonella_sp_analysis == "Positive" & salmonella_serotype1 == "Final result - characterization not available" ~ "No serotype data available",
      salmonella_sp_analysis == "Negative" ~ NA_character_,
      TRUE ~ salmonella_serotype1
    )
  )

write.csv(data_serotype, "data_serotype.csv")
```

```{r Descriptive Analysis for all data - Table 1 & STable 5}
### sample characteristics 
prevalence_data <- read.csv("data_serotype.csv", header=TRUE) %>%
  mutate(
    screening          = ifelse(salmonella_sp_analysis == "Positive", 1, 0),
    month              = factor(format(as.Date(collection_date), "%m"),
                                levels = sprintf("%02d", 1:12),
                                labels = month.abb),
    year = factor(format(as.Date(collection_date), "%y")),
    establishment_size  = factor(establishment_size,
                                 levels = c("Large","Small","Very Small")),
    product_type        = factor(product_type), 
    salmonella_highlevel = ifelse(!is.na(as.numeric(salmonella_quantitative_cfu_ml))&(as.numeric(salmonella_quantitative_cfu_ml)>=10), 1,0),
    salmonella_result = ifelse(salmonella_sp_analysis == "Positive" & !is.na(as.numeric(salmonella_quantitative_cfu_ml))&(as.numeric(salmonella_quantitative_cfu_ml)>=10), "Positive High-level", ifelse(salmonella_sp_analysis == "Positive" & is.na(as.numeric(salmonella_quantitative_cfu_ml)| salmonella_quantitative_cfu_ml == "<10"), "Positive no quant", "Not High-level") ) 
  )
### subset to high-level for all sample
prevalence_data_quant<-prevalence_data[prevalence_data$salmonella_result!="Positive no quant", ]



###### Table 1 - Salmonella Positive descriptive analysis #######
### descriptive statistics for primary analysis (Table 1)
##### Table 1 - Salmonella positive - establishment size 
### get the number and percentage
table(prevalence_data$establishment_size)
table(prevalence_data$establishment_size, prevalence_data$screening)
round(prop.table(table(prevalence_data$establishment_size, prevalence_data$screening), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data$establishment_size, prevalence_data$screening))

##### Table 1 - Salmonella positive - product type
### get the number and percentage
table(prevalence_data$product_type)
table(prevalence_data$product_type, prevalence_data$screening)
round(prop.table(table(prevalence_data$product_type, prevalence_data$screening), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data$product_type, prevalence_data$screening))

##### Table 1 - Salmonella positive - month
### get the number and percentage
table(prevalence_data$month)
table(prevalence_data$month, prevalence_data$screening)
round(prop.table(table(prevalence_data$month, prevalence_data$screening), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data$month, prevalence_data$screening))

##### Table 1 - Salmonella positive - year
### get the number and percentage
table(prevalence_data$year)
table(prevalence_data$year, prevalence_data$screening)
round(prop.table(table(prevalence_data$year, prevalence_data$screening), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data$year, prevalence_data$screening))


###### Table 1 - Salmonella high-level descriptive analysis #######
##### Table 1 - Salmonella high-level - establishment size 
### get the number and percentage
table(prevalence_data$establishment_size, prevalence_data$salmonella_result)
round(prop.table(table(prevalence_data$establishment_size, prevalence_data$salmonella_result), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data_quant$establishment_size, prevalence_data_quant$salmonella_highlevel))

##### Table 1 - Salmonella high-level - product type
### get the number and percentage
table(prevalence_data$product_type, prevalence_data$salmonella_result)
round(prop.table(table(prevalence_data$product_type, prevalence_data$salmonella_result), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data_quant$product_type, prevalence_data_quant$salmonella_highlevel))

##### Table 1 - Salmonella high-level - month
### get the number and percentage
table(prevalence_data$month, prevalence_data$salmonella_result)
round(prop.table(table(prevalence_data$month, prevalence_data$salmonella_result), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data_quant$month, prevalence_data_quant$salmonella_highlevel))

##### Table 1 - Salmonella high-level - year
### get the number and percentage
table(prevalence_data$year, prevalence_data$salmonella_result)
round(prop.table(table(prevalence_data$year, prevalence_data$salmonella_result), margin = 1),4)*100
#chi-square test
chisq.test(table(prevalence_data_quant$year, prevalence_data_quant$salmonella_highlevel))
```

```{r Secondary Analysis for positive quant data - Table 2 & STable 4}
#### descriptive statistics for secondary analysis 
### subset to positive sample only
positive_data <- prevalence_data[prevalence_data$screening == 1,]
positive_data <- prevalence_data[!is.na(prevalence_data$salmonella_quantitative_cfu_ml),]

### serotype virulence for positive sample - FSIS risk assessment virulence clustering
high_virulence <- c(
  "Enteritidis",
  "Typhimurium",
  "Hadar",
  "I 4,[5],12:i:-",
  "Newport",
  "Litchfield",
  "Dublin",
  "Muenchen"
)

low_virulence <- c(
  "Infantis",
  "Kentucky",
  "Schwarzengrund",
  "Alachua",
  "Thompson",
  "Braenderup",
  "Heidelberg",
  "Typhimurium - Possible Vaccine Strain",
  "Anatum",
  "Cerro",
  "Johannesburg",
  "Mbandaka",
  "Senftenberg",
  "Montevideo",
  "Oranienburg",
  "Uganda",
  "I -:r:1,5",
  "IIIa [1],13,23:g,z51:-",
  "I 7:-:1,5",
  "Barranquilla",
  "Derby",
  "Havana",
  "Indiana",
  "Liverpool",
  "Orion",
  "Widemarsh"
)

#serotypes w/o virulence data reported in risk assessment are excluded from statistical testing
noinf_virulence <- c(
  "NA",
  "",
  "NULL",
  "No serotype data available",                     
  "Final result - characterization not available"
)


positive_data <- positive_data %>%
  mutate(
    serotype_virulence = case_when(
      salmonella_serotype1 %in% high_virulence ~ "High-virulence",
      salmonella_serotype1 %in% low_virulence ~ "Low-virulence",
      is.na(salmonella_serotype1) | salmonella_serotype1 %in% noinf_virulence ~ "Noinf_virulence",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(serotype_virulence), !is.na(salmonella_highlevel)) %>%
  mutate(
    serotype_virulence = factor(serotype_virulence,
                             levels = c("Low-virulence", "High-virulence", "Noinf_virulence"))
  )


### serotype virulence for positive sample - ARS list of serotypes of concern
high_virulence_ARS <- c(
  "Enteritidis",
  "Typhimurium",
  "Hadar",
  "I 4,[5],12:i:-",
  "Newport",
  "Dublin",
  "Muenchen" ,
  "Infantis",
  "Braenderup",
  "Heidelberg"
)

low_virulence_ARS <- c(
  "Kentucky",
  "Schwarzengrund",
  "Alachua",
  "Thompson",
  "Litchfield",
  "Typhimurium - Possible Vaccine Strain",
  "Anatum",
  "Cerro",
  "Johannesburg",
  "Mbandaka",
  "Senftenberg",
  "Montevideo",
  "Oranienburg",
  "Uganda",
  "I -:r:1,5",
  "IIIa [1],13,23:g,z51:-",
  "I 7:-:1,5",
  "Barranquilla",
  "Derby",
  "Havana",
  "Indiana",
  "Liverpool",
  "Orion",
  "Widemarsh"
)

#serotypes w/o virulence data reported in risk assessment are excluded from statistical testing
noinf_virulence <- c(
  "NA",
  "",
  "NULL",
  "No serotype data available",                     
  "Final result - characterization not available"
)


positive_data <- positive_data %>%
  mutate(
    serotype_virulence_ARS = case_when(
      salmonella_serotype1 %in% high_virulence_ARS ~ "High-virulence",
      salmonella_serotype1 %in% low_virulence_ARS ~ "Low-virulence",
      is.na(salmonella_serotype1) | salmonella_serotype1 %in% noinf_virulence ~ "Noinf_virulence",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(serotype_virulence_ARS), !is.na(salmonella_highlevel)) %>%
  mutate(
    serotype_virulence_ARS = factor(serotype_virulence_ARS,
                             levels = c("Low-virulence", "High-virulence", "Noinf_virulence"))
  )

#relevel to make high-virulence as reference group 
positive_data$serotype_virulence <- relevel(
  factor(positive_data$serotype_virulence),
  ref = "High-virulence")

positive_data$serotype_virulence_ARS <- relevel(
  factor(positive_data$serotype_virulence_ARS),
  ref = "High-virulence")


###### Table 2. Descriptive analysis for stereotype classification ####
##FSIS approach
#get the number and percentage
table(positive_data$serotype_virulence)
table(positive_data$serotype_virulence, positive_data$salmonella_highlevel)
round(prop.table(table(positive_data$serotype_virulence, positive_data$salmonella_highlevel), margin = 1),4)*100


#### ARS approach
table(positive_data$serotype_virulence_ARS)
table(positive_data$serotype_virulence_ARS, positive_data$salmonella_highlevel)
round(prop.table(table(positive_data$serotype_virulence_ARS, positive_data$salmonella_highlevel), margin = 1),4)*100

#chi-square test
chisq.test(table(positive_data$serotype_virulence, positive_data$salmonella_highlevel))
chisq.test(table(positive_data$serotype_virulence_ARS, positive_data$salmonella_highlevel))
```

```{r Primary model & Establishment size_Product type - STable 2 & 3}
### Primary analysis and interaction term (Figure 2 & STable 1)

##### STable 1. multivariable mixed-effect logistic model #####
### create function to output OR and 95CI results
output_or_mixeffect <- function(model){
  round(exp(cbind(OR = fixef(model), confint(model, parm = "beta_", method = "Wald"))),2)
}

### multivariate mixed effect logistic regression with interaction 
multi_prevelance_mixeffect_int <- glmer(screening ~ establishment_size+product_type+month +year + establishment_size*product_type+ (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))
### output model summary 
summary(multi_prevelance_mixeffect_int)
### obtain OR and 95% CI
output_or_mixeffect(multi_prevelance_mixeffect_int)

### calculate ICC
var_establishment <- 0.5309   
ICC <- var_establishment /
       (var_establishment + (pi^2 / 3))
ICC


### get predicted proportion for establishment size and product type
emm <- emmeans(
  multi_prevelance_mixeffect_int,
  ~ establishment_size * product_type,
  type = "response"
)

emm_df<-as.data.frame(emm)
### specific OR for establishment size and product type (STable xx)
pairs(emm, by = "product_type", type = "response", infer = c(TRUE, TRUE), reverse = TRUE, adjust = "tukey")
pairs(emm, by = "establishment_size", type = "response", infer = c(TRUE, TRUE),reverse = TRUE, adjust = "tukey")


# 1. Establishment-level percentage positive
positive_percentage <- prevalence_data %>%
  group_by(establishment_size, product_type, establishment_id) %>%
  summarise(
    Total = sum(!is.na(screening)),
    Positive = sum(screening == 1, na.rm = TRUE),
    Positive_Percentage = Positive / Total ,
    .groups = "drop"
  )

# 2. Overall percentage positive across all samples
overall_percentage <- prevalence_data %>%
  group_by(establishment_size, product_type) %>%
  summarise(
    Total = sum(!is.na(screening)),
    Positive = sum(screening == 1, na.rm = TRUE),
    Overall_Percentage = Positive / Total ,
    .groups = "drop"
  )

```

```{r Establishment size_Product type visualization - Figure 2}
##### Figure 2. Salmonella positive by establishment size and product type ####
### by establishment size
sal_positive_prod_est<-ggplot(
  emm_df,
  aes(
    x =  establishment_size,
    y = prob,
    group = product_type,
    color = product_type
  )
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(ymin = asymp.LCL, ymax = asymp.UCL),
    width = 0.08,
    linewidth = 0.6
  ) +
    scale_color_manual(
    values = c(
      "Breast" = "#76B7B2",
      "Leg" = "#B07AA1"  ,
      "Wing" = "#3B5B92"
    )
  ) +
  scale_y_continuous(
    labels = percent_format(accuracy = 1),
    limits = c(0, 0.2),
    expand = expansion(mult = c(0, 0.05))
  ) +
  labs(
    x = "Establishment size",
    y = expression("Predicted "*italic("Salmonella")*" positive (%) generated from model"),
    color = "Product Type"
  ) +
  theme_classic(base_size = 12) +
  theme(
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold"),
    legend.position = "inside",
    legend.position.inside = c(0.02, 0.95),
    legend.justification = c(0, 1)
  )


### by product type
sal_positive_est_prod<-ggplot(
  emm_df,
  aes(
    x = product_type,
    y = prob,
    group = establishment_size,
    color = establishment_size
  )
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(ymin = asymp.LCL, ymax = asymp.UCL),
    width = 0.08,
    linewidth = 0.6
  ) +
  scale_color_manual(
    values = c(
      "Large" = "#E15759",
      "Small" = "#59A14F",
      "Very Small" = "#F28E2B"
    )
  ) +
  scale_y_continuous(
    labels = scales::percent_format(accuracy = 1),
    limits = c(0, 0.2),
    expand = expansion(mult = c(0, 0.05))
  ) +
  labs(
    x = "Product type",
    y = expression("Predicted "*italic("Salmonella")*" positive (%) generated from model"),
    color = "Establishment size"
  ) +
  theme_classic(base_size = 12) +
  theme(
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold"),
    legend.position = "inside",
    legend.position.inside = c(0.02, 0.95),
    legend.justification = c(0, 1)
  )



# 3. Plot
observed_sal_positive_prod_est<-ggplot(
  positive_percentage,
  aes(
    x = establishment_size,
    y = Positive_Percentage,
    fill = product_type
  )
) +
  geom_boxplot(
    position = position_dodge(width = 0.8),
    width = 0.7,
    outlier.shape = 21
  ) +
  
  geom_point(
    data = overall_percentage,
    aes(
      x = establishment_size,
      y = Overall_Percentage,
      group = product_type
    ),
    position = position_dodge(width = 0.8),
    shape = 18,
    size = 3,
    color = "black"
  ) +
  
  scale_fill_manual(
    values = c(
      "Breast" = "#76B7B2",
      "Leg" = "#B07AA1"  ,
      "Wing" = "#3B5B92"
    )
  ) +
  scale_y_continuous(
    labels = percent_format(accuracy = 1),
    limits = c(0, NA)
  ) +
  
  labs(
    x = "Establishment Size",
    y = expression("Observed "*italic("Salmonella")*" positive (%) within establishments"),
    fill = "Product Type"
  ) +
  theme_classic(base_size = 12) +
  theme(
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold"),
    legend.position = "inside",
    legend.background = element_blank(),
    legend.position.inside = c(0.02, 0.95),
    legend.justification = c(0, 1)
  )



# 3. Plot
observed_sal_positive_est_prod<-ggplot(
  positive_percentage,
  aes(
    x = product_type ,
    y = Positive_Percentage,
    fill = establishment_size
  )
) +
  geom_boxplot(
    position = position_dodge(width = 0.8),
    width = 0.7,
    outlier.shape = 21
  ) +
  
  # Overall percentage positive
  geom_point(
    data = overall_percentage,
    aes(
      x =product_type ,
      y = Overall_Percentage,
      group = establishment_size
    ),
    position = position_dodge(width = 0.8),
    shape = 18,
    size = 3,
    color = "black"
  ) +
  scale_fill_manual(
    values = c(
      "Large" = "#E15759",
      "Small" = "#59A14F",
      "Very Small" = "#F28E2B"
    )
  ) +
  scale_y_continuous(
    labels = percent_format(accuracy = 1),
    limits = c(0, NA)
  ) +
  
  labs(
    x = "Product Type ",
    y = expression("Observed "*italic("Salmonella")*" positive (%) within establishments"),
    fill = "Establishment Size"
  ) +
  theme_classic(base_size = 12) +
  theme(
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold"),
    legend.position = "inside",
    legend.background = element_blank(),
    legend.position.inside = c(0.02, 0.95),
    legend.justification = c(0, 1)
  )
observed_sal_positive_est_prod
#combined_sal_positive <- (observed_sal_positive_prod_est / observed_sal_positive_est_prod) | (sal_positive_prod_est / sal_positive_est_prod) + plot_layout(widths = c(1, 1),heights = c(1,1))

#combined_sal_positive


observed_column <-
  observed_sal_positive_prod_est /
  observed_sal_positive_est_prod +
  plot_layout(
    heights = c(1, 1),
    axes = "collect",
    axis_titles = "collect"
  )

predicted_column <-
  sal_positive_prod_est /
  sal_positive_est_prod +
  plot_layout(
    heights = c(1, 1),
    axes = "collect",
    axis_titles = "collect"
  )

combined_sal_positive <-
  observed_column | predicted_column


combined_sal_positive

ggsave(filename = "figures/EstsblishmentSize_Product_interaction.jpg", plot = combined_sal_positive, width = 12, height = 10, dpi = 300)

```

```{r Seasonal and temporal variation visualization - Figure 3}

# 1. Monthly prevalence of Salmonella positivity


prevalence_data <- prevalence_data %>%
  mutate(
    month_year = as.Date(
      format(as.Date(collection_date), "%Y-%m-01")
    )
  )


prevalence_parts <- do.call(rbind, lapply(
  sort(unique(prevalence_data$month_year)),
  function(m) {
    
    x <- prevalence_data$salmonella_sp_analysis[
      prevalence_data$month_year == m
    ]
    
    x <- x[!is.na(x)]
    
    n <- length(x)
    pos <- sum(x == "Positive")
    ci <- binom.test(pos, n)$conf.int
    
    data.frame(
      Month_Year = m,
      Month = format(m, "%b"),
      Year = format(m, "%Y"),
      Total = n,
      Positive = pos,
      Percent_Positive = pos / n,
      CI_Lower = ci[1],
      CI_Upper = ci[2]
    )
  }
))


prevalence_parts$Month <- factor(
  prevalence_parts$Month,
  levels = month.abb
)

prevalence_parts <- prevalence_parts %>%
  mutate(
    Month_num = as.numeric(format(Month_Year, "%m")),
    Year = factor(Year)
  )


# 2. Plot: Salmonella prevalence


p_prevalence_seasonal <- ggplot(
  prevalence_parts,
  aes(
    x = Month_num,
    y = Percent_Positive * 100,
    group = Year,
    color = Year
  )
) +
  geom_ribbon(
    aes(
      ymin = CI_Lower * 100,
      ymax = CI_Upper * 100,
      fill = Year
    ),
    alpha = 0.10,
    color = NA
  ) +
  
  geom_line(linewidth = 0.8) +
  
  geom_point(size = 2) +
  
  scale_x_continuous(
    breaks = 1:12,
    labels = month.abb
  ) +
  
  scale_color_manual(
    values = c(
      "2023" = "#4E79A7",
      "2024" = "#F28E2B",
      "2025" = "#59A14F"
    )
  ) +
  
  scale_fill_manual(
    values = c(
      "2023" = "#4E79A7",
      "2024" = "#F28E2B",
      "2025" = "#59A14F"
    )
  ) +
  
  labs(
    x = "Month",
    y = expression(
      "Observed "*italic("Salmonella")*" Positive (%) by year"
    ),
    #title = expression("(c) Seasonal variation of "*italic("Salmonella")*" Positive"),
    color = "Year",
    fill = "Year"
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))
  ) +
  
  theme_classic(base_size = 12) +
  theme(
    legend.position = "right",
    panel.grid.major.y = element_line(
      linewidth = 0.3,
      color = "grey90"
    )
  )



# 3. Monthly prevalence of Salmonella high-level contamination


highlevel_parts <- do.call(rbind, lapply(
  sort(unique(prevalence_data$month_year)),
  function(m) {
    
    x <- prevalence_data$salmonella_highlevel[
      prevalence_data$month_year == m
    ]
    
    x <- x[!is.na(x)]
    
    n <- length(x)
    pos <- sum(x == 1)
    ci <- binom.test(pos, n)$conf.int
    
    data.frame(
      Month_Year = m,
      Month = format(m, "%b"),
      Year = format(m, "%Y"),
      Total = n,
      Positive = pos,
      Percent_Positive = pos / n,
      CI_Lower = ci[1],
      CI_Upper = ci[2]
    )
  }
))

highlevel_parts$Month <- factor(
  highlevel_parts$Month,
  levels = month.abb
)

highlevel_parts <- highlevel_parts %>%
  mutate(
    Month_num = as.numeric(format(Month_Year, "%m")),
    Year = factor(Year)
  )



# 4. Plot: Salmonella high-level contamination


p_highlevel_seasonal <- ggplot(
  highlevel_parts,
  aes(
    x = Month_num,
    y = Percent_Positive * 100,
    group = Year,
    color = Year
  )
) +
  
  geom_ribbon(
    aes(
      ymin = CI_Lower * 100,
      ymax = CI_Upper * 100,
      fill = Year
    ),
    alpha = 0.10,
    color = NA
  ) +
  
  geom_line(linewidth = 0.8) +
  
  geom_point(size = 2) +
  
  scale_x_continuous(
    breaks = 1:12,
    labels = month.abb
  ) +
  
  scale_color_manual(
    values = c(
      "2023" = "#2F5597",
      "2024" = "#C55A11",
      "2025" = "#3B7A3A"
    )
  ) +
  
  scale_fill_manual(
    values = c(
      "2023" = "#2F5597",
      "2024" = "#C55A11",
      "2025" = "#3B7A3A"
    )
  ) +
  
  labs(
    x = "Month",
    y = expression(
      "Observed "*italic("Salmonella")*" High-Level (%) by year"
    ),
    #title = expression("(d) Seasonal variation of High-level "*italic("Salmonella")*""),
    color = "Year",
    fill = "Year"
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))
  ) +
  
  theme_classic(base_size = 12) +
  theme(
    legend.position = "right",
    panel.grid.major.y = element_line(
      linewidth = 0.3,
      color = "grey90"
    )
  )


# 5. Combine the two figures using patchwork


combined_plot_season <- p_prevalence_seasonal / p_highlevel_seasonal +
  plot_layout(guides = "collect") &
  theme(
    legend.position = "right"
  )

combined_plot_season


#ggsave("seasonal_plot.jpg", seasonal_plot, width = 10,height = 6)


# 1. CREATE MONTH-YEAR


prevalence_data <- prevalence_data %>%
  mutate(
    month_year = as.Date(
      format(as.Date(collection_date), "%Y-%m-01")
    )
  )



# 2. SALMONELLA PREVALENCE

prevalence_parts <- do.call(rbind, lapply(
  sort(unique(prevalence_data$month_year)),
  function(m) {
    
    x <- prevalence_data$salmonella_sp_analysis[
      prevalence_data$month_year == m
    ]
    
    x <- x[!is.na(x)]
    
    n <- length(x)
    pos <- sum(x == "Positive")
    
    ci <- binom.test(pos, n)$conf.int
    
    data.frame(
      Month_Year = m,
      Month = format(m, "%b"),
      Year = format(m, "%Y"),
      Total = n,
      Positive = pos,
      Percent_Positive = pos / n,
      CI_Lower = ci[1],
      CI_Upper = ci[2]
    )
  }
))

prevalence_parts$Month <- factor(
  prevalence_parts$Month,
  levels = month.abb
)



# 3. B-SPLINE MODEL FOR SALMONELLA PREVALENCE


prevalence_bs_model <- glm(
  cbind(Positive, Total - Positive) ~
    bs(as.numeric(Month_Year), df = 5),
  data = prevalence_parts,
  family = binomial
)

prevalence_pred_data <- data.frame(
  Month_Year = seq(
    min(prevalence_parts$Month_Year),
    max(prevalence_parts$Month_Year),
    by = "month"
  )
)

prevalence_pred <- predict(
  prevalence_bs_model,
  newdata = prevalence_pred_data,
  type = "link",
  se.fit = TRUE
)

prevalence_pred_data <- prevalence_pred_data %>%
  mutate(
    fit = plogis(prevalence_pred$fit),
    lower = plogis(
      prevalence_pred$fit -
        1.96 * prevalence_pred$se.fit
    ),
    upper = plogis(
      prevalence_pred$fit +
        1.96 * prevalence_pred$se.fit
    )
  )



# 4. PLOT 1: SALMONELLA PREVALENCE


p_prevalence <- ggplot() +
  
  # Observed exact 95% CI
  geom_ribbon(
    data = prevalence_parts,
    aes(
      x = Month_Year,
      ymin = CI_Lower * 100,
      ymax = CI_Upper * 100
    ),
    fill = "grey70",
    alpha = 0.35
  ) +
  
  # Observed prevalence
  geom_point(
    data = prevalence_parts,
    aes(
      x = Month_Year,
      y = Percent_Positive * 100
    ),
    size = 2,
    color = "black"
  ) +
  
  # B-spline 95% CI
  geom_ribbon(
    data = prevalence_pred_data,
    aes(
      x = Month_Year,
      ymin = lower * 100,
      ymax = upper * 100
    ),
    fill = "#9C8AC4",
    alpha = 0.20
  ) +
  
  # B-spline fitted prevalence
  geom_line(
    data = prevalence_pred_data,
    aes(
      x = Month_Year,
      y = fit * 100
    ),
    color = "#9C8AC4",
    linewidth = 1.2
  ) +
  
  labs(
    x = "Time",
    y = expression("Observed "*italic("Salmonella")*" Positve (%) over time")
    #title = expression("(a) Temporal trend of "*italic("Salmonella")*" Positive")
  ) +
  
  scale_x_date(
    date_breaks = "3 months",
    date_labels = "%b\n%Y",
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))
  ) +
  
  theme_classic(base_size = 12) +
  theme(
    axis.text.x = element_text(
      angle = 0,
      hjust = 1
    ),
    panel.grid.major.y = element_line(
      linewidth = 0.3,
      color = "grey90"
    ),
    plot.title = element_text(face = "bold")
  )



# 5. HIGH-LEVEL SALMONELLA


high_level_parts <- do.call(rbind, lapply(
  sort(unique(prevalence_data$month_year)),
  function(m) {
    
    x <- prevalence_data$salmonella_result[
      prevalence_data$month_year == m
    ]
    
    x <- x[!is.na(x)]
    
    n <- length(x)
    high_level <- sum(x == "Positive High-level")
    
    ci <- binom.test(high_level, n)$conf.int
    
    data.frame(
      Month_Year = m,
      Month = format(m, "%b"),
      Year = format(m, "%Y"),
      Total = n,
      High_Level = high_level,
      Percent_High_Level = high_level / n,
      CI_Lower = ci[1],
      CI_Upper = ci[2]
    )
  }
))

high_level_parts$Month <- factor(
  high_level_parts$Month,
  levels = month.abb
)



# 6. B-SPLINE MODEL FOR HIGH-LEVEL SALMONELLA


high_level_bs_model <- glm(
  cbind(High_Level, Total - High_Level) ~
    bs(as.numeric(Month_Year), df = 5),
  data = high_level_parts,
  family = binomial
)

high_level_pred_data <- data.frame(
  Month_Year = seq(
    min(high_level_parts$Month_Year),
    max(high_level_parts$Month_Year),
    by = "month"
  )
)

high_level_pred <- predict(
  high_level_bs_model,
  newdata = high_level_pred_data,
  type = "link",
  se.fit = TRUE
)

high_level_pred_data <- high_level_pred_data %>%
  mutate(
    fit = plogis(high_level_pred$fit),
    lower = plogis(
      high_level_pred$fit -
        1.96 * high_level_pred$se.fit
    ),
    upper = plogis(
      high_level_pred$fit +
        1.96 * high_level_pred$se.fit
    )
  )



# 7. PLOT 2: HIGH-LEVEL SALMONELLA


p_high_level <- ggplot() +
  
  # Observed exact 95% CI
  geom_ribbon(
    data = high_level_parts,
    aes(
      x = Month_Year,
      ymin = CI_Lower * 100,
      ymax = CI_Upper * 100
    ),
    fill = "grey70",
    alpha = 0.35
  ) +
  
  # Observed high-level prevalence
  geom_point(
    data = high_level_parts,
    aes(
      x = Month_Year,
      y = Percent_High_Level * 100
    ),
    size = 2,
    color = "black"
  ) +
  
  # B-spline 95% CI
  geom_ribbon(
    data = high_level_pred_data,
    aes(
      x = Month_Year,
      ymin = lower * 100,
      ymax = upper * 100
    ),
    fill = "#A67C6B",
    alpha = 0.20
  ) +
  
  # B-spline fitted high-level prevalence
  geom_line(
    data = high_level_pred_data,
    aes(
      x = Month_Year,
      y = fit * 100
    ),
    color = "#A67C6B",
    linewidth = 1.2
  ) +
  
  labs(
    x = "Time",
    y = expression("Observed High-level "*italic("Salmonella")*" (%) over time")
    #title = expression("(b) Temporal trend of High-level "*italic("Salmonella")*"")
  ) +
  
   scale_x_date(
    date_breaks = "3 months",
    date_labels = "%b\n%Y",
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))
  ) +
  
  theme_classic(base_size = 12) +
  theme(
    axis.text.x = element_text(
      angle = 0,
      hjust = 1
    ),
    panel.grid.major.y = element_line(
      linewidth = 0.3,
      color = "grey90"
    ),
    plot.title = element_text(face = "bold")
  )



# 8. COMBINE THE TWO PLOTS

combined_plot_temporal <- p_prevalence / p_high_level +
  plot_layout(heights = c(1, 1))

combined_plot_temporal


combined_plot_all <- 
  (p_prevalence  | p_prevalence_seasonal ) /
  ( p_high_level | p_highlevel_seasonal) +
  plot_layout(
    widths = c(1, 1),
    heights = c(1, 1)
  )

combined_plot_all

ggsave("figures/salmonella_temporal.jpg", combined_plot_all, width = 12,height = 9)

```

```{r regression model - Salmonella positive in all - STable 2 & STable 10}
###### sensitivity analysis for model selection (supplemental table 1)
model_primary <- glmer(screening ~ establishment_size+product_type+month +year + establishment_size*product_type+ (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_2 <- glmer(screening ~ establishment_size+product_type+month +year + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_3<-glm(screening ~ establishment_size+product_type+month +year + establishment_size*product_type, data = prevalence_data, family = binomial)

model_4<-glmer(screening ~ establishment_size+product_type +year + establishment_size*product_type+ (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_5<-glmer(screening ~ establishment_size+product_type +month + establishment_size*product_type+ (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_6<- glmer(screening ~ establishment_size+product_type + establishment_size*product_type+ (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_7 <- glmer(screening ~ establishment_size+product_type + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_8 <- glmer(screening ~ establishment_size+month +year + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))


model_9 <- glmer(screening ~ establishment_size+product_type+month +year + establishment_size*month + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_10<- glmer(screening ~ establishment_size+product_type+month +year + establishment_size*year + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))
  
  
summary(model_10)
anova(model_primary, model_10, test="Chisq")

var_establishment <- 0.5303   

ICC <- var_establishment /
       (var_establishment + (pi^2 / 3))

ICC

output_or_mixeffect(model_6)
```

```{r nested model - univariable and multivriable - STable 9}
## mixed-effect model for prevalence- supplemental table 3
### univariate
uni_estsize_mixeffect <- glmer(screening ~ establishment_size + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"))
uni_prodtype_mixeffect <- glmer(screening ~ product_type + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"))
uni_month_mixeffect <- glmer(screening ~ month + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"))
uni_year_mixeffect <- glmer(screening ~ year + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"))

summary(uni_estsize_mixeffect)
summary(uni_prodtype_mixeffect)
summary(uni_month_mixeffect)
summary(uni_year_mixeffect)

### multivariate
multi_prevelance_mixeffect <- glmer(screening ~ establishment_size+product_type+month +year + (1 | establishment_id), data = prevalence_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))
summary(multi_prevelance_mixeffect)


output_or_mixeffect(uni_estsize_mixeffect)
output_or_mixeffect(uni_prodtype_mixeffect)
output_or_mixeffect(uni_month_mixeffect)
output_or_mixeffect(uni_year_mixeffect)
output_or_mixeffect(multi_prevelance_mixeffect)

### random effect ICC calculation 
var_establishment <- 0.5423

ICC <- var_establishment /
       (var_establishment + (pi^2 / 3))

ICC
```

```{r regression model - high-level salmonella in all - Stable 2}
model_primary_high <- glmer(salmonella_highlevel ~ establishment_size*product_type+month +year + (1 | establishment_id), data = prevalence_data_quant, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

summary(model_primary_high)
output_or_mixeffect(model_primary_high)

var_establishment <- 0.7103      

ICC <- var_establishment /
       (var_establishment + (pi^2 / 3))

ICC

model_high_2<- glmer(salmonella_highlevel ~ establishment_size+product_type+month +year + (1 | establishment_id), data = prevalence_data_quant, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_3<- glmer(salmonella_highlevel ~ establishment_size*product_type+month + (1 | establishment_id), data = prevalence_data_quant, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_4<- glmer(salmonella_highlevel ~ establishment_size*product_type+year + (1 | establishment_id), data = prevalence_data_quant, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_5<- glmer(salmonella_highlevel ~ establishment_size+month+year + (1 | establishment_id), data = prevalence_data_quant, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_6<- glmer(salmonella_highlevel ~ product_type+month+year + (1 | establishment_id), data = prevalence_data_quant, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))


anova(model_primary_high, model_high_6, test = "Chisq")
```

```{r regression model - high-level salmonella in positive - STable 6}

model_primary_high_inpos <- glmer(salmonella_highlevel ~ establishment_size+product_type+month +year+serotype_virulence + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))


model_primary_high_inpos <- glmer(salmonella_highlevel ~  year+ (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

summary(model_primary_high_inpos)
output_or_mixeffect(model_primary_high_inpos)


model_primary_high_inpos_2 <- glmer(salmonella_highlevel ~ establishment_size+product_type+month +year+serotype_virulence_ARS + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))


summary(model_primary_high_inpos_2)
output_or_mixeffect(model_primary_high_inpos_2)


var_establishment <- 0.3192      

ICC <- var_establishment /
       (var_establishment + (pi^2 / 3))

ICC

anova(model_high_inpos_2, model_primary_high_inpos_2)

model_high_inpos_2<- glmer(salmonella_highlevel ~ establishment_size+product_type+month +year + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))
summary(model_high_inpos_2)

model_high_inpos_3<- glmer(salmonella_highlevel ~ establishment_size+product_type+month+serotype_virulence + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_inpos_4<- glmer(salmonella_highlevel ~ establishment_size+product_type +year+serotype_virulence + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_inpos_5<- glmer(salmonella_highlevel ~ establishment_size+month +year+serotype_virulence + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_inpos_6<- glmer(salmonella_highlevel ~ product_type+month +year+serotype_virulence + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))

model_high_inpos_7 <- glmer(salmonella_highlevel ~ establishment_size*product_type+month +year+serotype_virulence + (1 | establishment_id), data = positive_data, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 200000)))


anova(model_primary_high_inpos, model_high_inpos_7)
```

```{r establishment categorization}
#dataframe - PREVALENCE
fiftytwo_results_prevalence<-data.frame(
  establishment_id=integer(),
  rolling_window=character(), 
  start_date=character(), 
  end_date=character(), 
  n_pos=integer(),
  n_pos_adj=integer(),
  percent_pos=integer(),
  percent_pos_adj=numeric(),
  n_neg=integer(),
  percent_neg=numeric(),
  total_sample_no = integer(),
  n_pos_breast = integer(),
  n_neg_breast = integer(),
  n_pos_leg = integer(),
  n_neg_leg = integer(),
  n_pos_wing = integer(),
  n_neg_wing = integer(),
  rw_category = character(),
  establishment_size=character()
  )

## PREVALENCE BASED STANDARDS
data <- read.csv("data_serotype.csv", header = TRUE)
data$collection_date <- as.Date(data$collection_date)

end_dates <- as.Date(unlist(list(
  "2025-09-27",
  "2025-08-30",
  "2025-07-26",
  "2025-06-28",
  "2025-05-31",
  "2025-04-26",
  "2025-03-29",
  "2025-02-22",
  "2025-01-25",
  "2024-12-28",
  "2024-11-30",
  "2024-10-26",
  "2024-09-28",
  "2024-08-31",
  "2024-07-27",
  "2024-06-29",
  "2024-05-25",
  "2024-04-27",
  "2024-03-30",
  "2024-02-24",
  "2024-01-27",
  "2023-12-30"
)))

start_dates <- as.Date(c(
  "2024-09-29",
  "2024-09-01",
  "2024-07-28",
  "2024-06-30",
  "2024-06-02",
  "2024-04-28",
  "2024-03-31",
  "2024-02-25",
  "2024-01-28",
  "2023-12-31",
  "2023-12-03",
  "2023-10-29",
  "2023-10-01",
  "2023-09-03",
  "2023-07-30",
  "2023-07-02",
  "2023-05-28",
  "2023-04-30",
  "2023-04-02",
  "2023-02-26",
  "2023-01-29",
  "2023-01-01"
))


for (j in 1:length(establishment_ids)) {
  
  for (i in seq_along(start_dates)) {
    
    # Use the predefined start and end dates
    fiftytwo_start <- start_dates[i]
    fiftytwo_end <- end_dates[i]
    fiftytwo_interval <- interval(fiftytwo_start, fiftytwo_end)
    
    # Check whether there are any samples in this window
    if (sum(
      data$collection_date %within% fiftytwo_interval &
      data$establishment_id == establishment_ids[j]
    ) == 0) {
      next
    }
    
    new_results <- data.frame(
      
      # Specify start and end dates
      rolling_window = as.character(i),
      start_date = as.character(fiftytwo_start),
      end_date = as.character(fiftytwo_end),
      
      # Overall positive/negative
      n_pos = sum(
        data$salmonella_sp_analysis == "Positive" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j]
      ),
      
      n_neg = sum(
        data$salmonella_sp_analysis == "Negative" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j]
      ),
      
      # Positive by product type
      n_pos_breast = sum(
        data$salmonella_sp_analysis == "Positive" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j] &
        data$product_type == "Breast"
      ),
      
      n_pos_leg = sum(
        data$salmonella_sp_analysis == "Positive" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j] &
        data$product_type == "Leg"
      ),
      
      n_pos_wing = sum(
        data$salmonella_sp_analysis == "Positive" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j] &
        data$product_type == "Wing"
      ),
      
      # Negative by product type
      n_neg_breast = sum(
        data$salmonella_sp_analysis == "Negative" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j] &
        data$product_type == "Breast"
      ),
      
      n_neg_leg = sum(
        data$salmonella_sp_analysis == "Negative" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j] &
        data$product_type == "Leg"
      ),
      
      n_neg_wing = sum(
        data$salmonella_sp_analysis == "Negative" &
        data$collection_date %within% fiftytwo_interval &
        data$establishment_id == establishment_ids[j] &
        data$product_type == "Wing"
      ),
      
      establishment_id = establishment_ids[j],
      stringsAsFactors = FALSE
    )
    
    new_results$total_sample_no <- 
      new_results$n_pos + new_results$n_neg
    
    new_results$n_pos_adj <- ifelse(
      new_results$total_sample_no < 52 & new_results$n_pos > 0,
      new_results$n_pos - 1,
      new_results$n_pos
    )
    
    new_results$percent_pos <- 
      (new_results$n_pos / new_results$total_sample_no) * 100
    
    new_results$percent_pos_adj <- 
      (new_results$n_pos_adj / new_results$total_sample_no) * 100
    
    new_results$percent_neg <- 
      (new_results$n_neg / new_results$total_sample_no) * 100
    
    new_results$rw_category <- ifelse(
      new_results$total_sample_no < 10 &
        new_results$total_sample_no > 0 &
        new_results$n_pos <= 8,
      NA,
      ifelse(
        new_results$percent_pos_adj > 15.4,
        "3",
        ifelse(
          new_results$percent_pos_adj > 7.7 &
            new_results$percent_pos_adj <= 15.4,
          "2",
          ifelse(
            new_results$percent_pos_adj <= 7.7,
            "1",
            ""
          )
        )
      )
    )
    
    row <- data[
      which(data$establishment_id == establishment_ids[j])[1],
    ]
    
    new_results$establishment_size <- row$establishment_size
    
    # Combine results
    fiftytwo_results_prevalence <- bind_rows(
      fiftytwo_results_prevalence,
      new_results
    )
  }
}

write.csv(fiftytwo_results_prevalence, "prevalencebasedresults_withNAcategory_monthly.csv")
```

```{r establishment categorization - Figure 4}

plot_data <- read.csv("prevalencebasedresults_withNAcategory_monthly.csv")
plot_data$end_date <- anydate(plot_data$end_date)
plot_data <- subset(plot_data, plot_data$end_date > "2023-01-01")
plot_data <- plot_data %>%
  count(
    end_date,
    #establishment_id,
    establishment_size,
    total_sample_no,
    percent_pos_adj,
    name = "n"
  )

# 1. Prepare the Data
# --- SCATTER DATA ---
plot_data <- plot_data %>%
  mutate(
    category = cut(
      percent_pos_adj,
      breaks = c(-Inf, 7.7, 15.4, Inf),
      labels = c("Category 1", "Category 2", "Category 3"),
      right = FALSE
    ),
    scatter_color = ifelse(
      total_sample_no < 10,
      "Less than 10 samples",
      as.character(category)
    )
  )

# --- BAR DATA ---
bar_total <- plot_data %>%
  group_by(establishment_size, category) %>%
  summarise(
    total_est = sum(n),
    .groups = "drop"
  )

bar_less10 <- plot_data %>%
  filter(total_sample_no < 10) %>%
  group_by(establishment_size, category) %>%
  summarise(
    less10_est = sum(n),
    .groups = "drop"
  )

bar_data <- bar_total %>%
  left_join(
    bar_less10,
    by = c("establishment_size", "category")
  ) %>%
  mutate(
    less10_est = tidyr::replace_na(less10_est, 0)
  ) %>%
  group_by(establishment_size) %>%
  mutate(
    proportion = total_est / sum(total_est),
    less10_proportion = less10_est / sum(total_est),
    ge10_proportion = proportion - less10_proportion
  ) %>%
  ungroup()

# Consistent color palette
cat_colors <- c(
  "Category 1" = "#4C956C",
  "Category 2" = "#F4A261",
  "Category 3" = "#C8553D"
)

# Get the first/top establishment-size level
top_facet <- levels(factor(plot_data$establishment_size))[1]

# Labels shown only in the top facet
line_labels <- data.frame(
  establishment_size = top_facet,
  x = c(3.5, 30, 60),
  y = c(57, 57, 57),
  label = c(
    "Number of samples <10",
    "10≤ Number of samples <52",
    "Number of samples ≥52"
  )
)

# --- SCATTER PLOT ---
p_scatter <- ggplot(
  plot_data,
  aes(
    x = total_sample_no,
    y = percent_pos_adj,
    size = n,
    color = scatter_color
  )
) +
  geom_point(alpha = 0.7) +

  geom_vline(
    xintercept = 10,
    linetype = "dashed",
    color = "gray50",
    linewidth = 0.8
  ) +

  geom_vline(
    xintercept = 52,
    linetype = "dashed",
    color = "gray30",
    linewidth = 0.8
  ) +

  # Labels only in top facet
  geom_text(
    data = line_labels,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    size = 3.2,
    color = "gray30"
  ) +

  facet_wrap(~ establishment_size, ncol = 1) +

  scale_size_area(
    max_size = 12,
    breaks = c(5, 10, 20),
    name = "Number of moving windows"
  ) +

  scale_color_manual(
    values = c(
      "Category 1" = "#4C956C",
      "Category 2" = "#F4A261",
      "Category 3" = "#C8553D",
      "Less than 10 samples" = "gray50"
    ),
    guide = "none"
  ) +

  scale_x_continuous(
    breaks = seq(0, 65, 5),
    limits = c(0, 65)
  ) +

  scale_y_continuous(
    breaks = seq(0, 60, 10),
    limits = c(0, 60)
  ) +

  labs(
    x = "Number of samples collected from one establishment in one moving window",
    y = "Percent positive for one establishment in one moving window"
  ) +

  theme_bw(base_size = 15) +
  theme(
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "gray90")
  )

# --- BAR PLOT ---
p_bar <- ggplot(
  bar_data,
  aes(x = category)
) +

  # Colored portion: >=10 samples
  geom_col(
    aes(y = ge10_proportion, fill = category),
    color = "black",
    linewidth = 0.2,
    alpha = 0.8
  ) +

  # Gray portion: <10 samples, stacked ON TOP
  geom_rect(
    aes(
      xmin = as.numeric(category) - 0.45,
      xmax = as.numeric(category) + 0.45,
      ymin = ge10_proportion,
      ymax = proportion,
      fill = "Number of samples <10"
    ),
    color = "black",
    linewidth = 0.2
  ) +

  # >=10 percentage inside colored area
  geom_text(
    aes(
      y = ge10_proportion / 2,
      label = scales::percent(ge10_proportion, accuracy = 0.1)
    ),
    size = 4.2
  ) +

  # Overall percentage at top
  geom_text(
    aes(
      y = proportion,
      label = scales::percent(proportion, accuracy = 0.1)
    ),
    vjust = -0.5,
    size = 4.5
  ) +

  facet_wrap(~ establishment_size, ncol = 1) +

  scale_fill_manual(
    values = c(
      cat_colors,
      "Number of samples <10" = "gray50"
    ),
    breaks = c(
      "Category 1",
      "Category 2",
      "Category 3",
      "Number of samples <10"
    ),
    name = NULL
  ) +

  scale_y_continuous(
    labels = scales::percent_format(),
    limits = c(0, 1.1)
  ) +

  labs(
    x = NULL,
    y = "Proportion of Categorization"
  ) +

  theme_bw(base_size = 15) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# --- COMBINE WITH PATCHWORK ---
final_plot <- p_scatter + p_bar + 
  plot_layout(widths = c(3, 1), guides = "collect") & 
  theme(legend.position = "bottom") 

# Display the plot
final_plot

ggsave( "figures/percent_positive_by_sample_size_withprop_monthly_grey.jpg", plot = final_plot, width = 12, height = 9, dpi = 600)
```

```{r category proportion comparison - STable 7}
plot_data_test <- read.csv("prevalencebasedresults_withNAcategory_monthly.csv")
plot_data_test$end_date <- anydate(plot_data_test$end_date)
plot_data_test <- subset(plot_data_test, plot_data_test$end_date > "2023-01-01")
plot_data_test <- plot_data_test %>%
  count(
    end_date,
    establishment_id,
    establishment_size,
    total_sample_no,
    percent_pos_adj,
    name = "n"
  )

# 1. Prepare the Data
# --- SCATTER DATA ---
plot_data_test <- plot_data_test %>%
  mutate(
    category = cut(
      percent_pos_adj,
      breaks = c(-Inf, 7.7, 15.4, Inf),
      labels = c("Category 1", "Category 2", "Category 3"),
      right = FALSE
    ),
    scatter_color = ifelse(
      total_sample_no < 10,
      "Less than 10 samples",
      as.character(category)
    )
  )


table(plot_data_test$establishment_size)
table(plot_data_test$establishment_size,plot_data_test$category)

prop.table(table(plot_data_test$establishment_size,plot_data_test$category), margin = 1)

chisq.test(table(plot_data_test$category, plot_data_test$establishment_size))


# Overall contingency table
tab <- table(
  plot_data_test$category,
  plot_data_test$establishment_size
)

# Overall chi-square test
chisq.test(tab)

# Pairwise post-hoc chi-square tests
sizes <- colnames(tab)

pairs <- combn(sizes, 2, simplify = FALSE)

posthoc <- do.call(rbind, lapply(pairs, function(x) {

  temp_tab <- tab[, x, drop = FALSE]

  test <- chisq.test(temp_tab)

  data.frame(
    Group1 = x[1],
    Group2 = x[2],
    Chi_square = unname(test$statistic),
    df = unname(test$parameter),
    p_value = test$p.value
  )
}))

# Adjust for 3 pairwise comparisons
posthoc$p_adjusted <- p.adjust(
  posthoc$p_value,
  method = "holm"
)

posthoc


plot_data_gt10 <- plot_data_test[plot_data_test$scatter_color!="Less than 10 samples",]

table(plot_data_gt10$establishment_size)

table(plot_data_gt10$establishment_size,plot_data_gt10$category)

prop.table(table(plot_data_gt10$establishment_size,plot_data_gt10$category), margin = 1)

chisq.test(table(plot_data_gt10$category, plot_data_gt10$establishment_size))


# Overall contingency table
tab_gt10 <- table(
  plot_data_gt10$category,
  plot_data_gt10$establishment_size
)

# Overall chi-square test
chisq.test(tab_gt10)

# Pairwise post-hoc chi-square tests
sizes <- colnames(tab_gt10)

pairs <- combn(sizes, 2, simplify = FALSE)

posthoc <- do.call(rbind, lapply(pairs, function(x) {

  temp_tab <- tab_gt10[, x, drop = FALSE]

  test <- chisq.test(temp_tab)

  data.frame(
    Group1 = x[1],
    Group2 = x[2],
    Chi_square = unname(test$statistic),
    df = unname(test$parameter),
    p_value = test$p.value
  )
}))

# Adjust for 3 pairwise comparisons
posthoc$p_adjusted <- p.adjust(
  posthoc$p_value,
  method = "holm"
)

posthoc

```

```{r Salmonella positive + establishment category over time - Figure 5}
# Calculate category proportions
plot_data_filtered <- plot_data %>%
  filter(total_sample_no >= 10)

plot_prop <- plot_data_filtered %>%
  group_by(end_date, establishment_size, category) %>%
  summarise(
    n = sum(n),
    .groups = "drop"
  ) %>%
  group_by(end_date, establishment_size) %>%
  mutate(
    proportion = n / sum(n) * 100
  ) %>%
  ungroup()

# Calculate "All" establishments
plot_all <- plot_data %>%
  group_by(end_date, category) %>%
  summarise(
    n = sum(n),
    .groups = "drop"
  ) %>%
  group_by(end_date) %>%
  mutate(
    proportion = n / sum(n) * 100,
    establishment_size = "All"
  ) %>%
  ungroup()

# Combine All + establishment size groups
plot_prop <- bind_rows(plot_all, plot_prop) %>%
  mutate(
    establishment_size = factor(
      establishment_size,
      levels = c("All", "Large", "Small", "Very Small")
    ),
    category = factor(
      category,
      levels = c("Category 1", "Category 2", "Category 3")
    )
  )

# Category colors
cat_colors <- c(
  "Category 1" = "#4C956C",
  "Category 2" = "#F4A261",
  "Category 3" = "#C8553D"
)

# Calculate category proportions by establishment size
plot_prop <- plot_data %>%
  group_by(end_date, establishment_size, category) %>%
  summarise(
    n = sum(n),
    .groups = "drop"
  ) %>%
  group_by(end_date, establishment_size) %>%
  mutate(
    proportion = n / sum(n) * 100
  ) %>%
  ungroup()

# Calculate "All" establishments
plot_all <- plot_data %>%
  group_by(end_date, category) %>%
  summarise(
    n = sum(n),
    .groups = "drop"
  ) %>%
  group_by(end_date) %>%
  mutate(
    proportion = n / sum(n) * 100,
    establishment_size = "All"
  ) %>%
  ungroup()

# Combine
plot_prop <- bind_rows(plot_all, plot_prop) %>%
  mutate(
    establishment_size = factor(
      establishment_size,
      levels = c("All", "Large", "Small", "Very Small")
    ),
    category = factor(
      category,
      levels = c("Category 1", "Category 2", "Category 3")
    )
  )

# Plot
category_overtime <- ggplot(
  plot_prop,
  aes(
    x = end_date,
    y = proportion,
    color = category,
    group = category
  )
) +

  # Trend lines
  geom_line(
    linewidth = 0.9
  ) +

  # Observed values
  geom_point(
    size = 2,
    stroke = 0
  ) +

  facet_wrap(
    ~ establishment_size,
    ncol = 1
  ) +

  scale_color_manual(
    values = cat_colors,
    name = "Category"
  ) +

  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 20),
    labels = function(x) paste0(x, "%"),
    expand = expansion(mult = c(0, 0.02))
  ) +

  scale_x_date(
    date_breaks = "3 months",
    date_labels = "%b\n%Y",
    expand = expansion(mult = c(0.01, 0.02))
  ) +

  labs(
    x = "Time",
    y = "Proportion of establishments",
    title = "(b) Proportion of establishment catgeories over time"
  ) +

  theme_classic(base_size = 15) +

  theme(
    legend.position = "right",

    # Facet labels
    strip.background = element_rect(
      fill = "grey92",
      color = NA
    ),
    strip.text = element_text(
      face = "bold",
      size = 12
    ),

    # Axes
    axis.text.x = element_text(
      angle = 0,
      hjust = 1,
      vjust = 1
    ),

    # Light horizontal reference lines
    panel.grid.major.y = element_line(
      color = "grey90",
      linewidth = 0.3
    ),
    panel.grid.minor = element_blank(),

    # Space between panels
    panel.spacing = unit(0.8, "lines"),

    # Legend
    legend.title = element_text(face = "bold"),
    legend.key.width = unit(1.2, "cm")
  )

category_overtime

#ggsave("category_plot_byest_overtime.jpg", category_overtime, width = 10, height = 15)


# Create month-year
prevalence_data <- prevalence_data %>%
  mutate(
    month_year = as.Date(
      format(as.Date(collection_date), "%Y-%m-01")
    )
  )


# 1. Monthly prevalence by establishment size

prevalence_parts <- prevalence_data %>%
  filter(!is.na(salmonella_sp_analysis),
         !is.na(establishment_size)) %>%
  group_by(month_year, establishment_size) %>%
  summarise(
    Total = n(),
    Positive = sum(salmonella_sp_analysis == "Positive"),
    .groups = "drop"
  ) %>%
  rowwise() %>%
  mutate(
    CI = list(binom.test(Positive, Total)$conf.int),
    CI_Lower = CI[1],
    CI_Upper = CI[2]
  ) %>%
  ungroup() %>%
  select(-CI) %>%
  mutate(
    Percent_Positive = Positive / Total,
    Establishment_Size = as.character(establishment_size)
  )


# 2. Overall monthly prevalence


prevalence_all <- prevalence_data %>%
  filter(!is.na(salmonella_sp_analysis)) %>%
  group_by(month_year) %>%
  summarise(
    Total = n(),
    Positive = sum(salmonella_sp_analysis == "Positive"),
    .groups = "drop"
  ) %>%
  rowwise() %>%
  mutate(
    CI = list(binom.test(Positive, Total)$conf.int),
    CI_Lower = CI[1],
    CI_Upper = CI[2]
  ) %>%
  ungroup() %>%
  select(-CI) %>%
  mutate(
    Percent_Positive = Positive / Total,
    Establishment_Size = "All"
  )

# 3. Combine


prevalence_plot <- bind_rows(
  prevalence_all,
  prevalence_parts
) %>%
  mutate(
    Month_Year = month_year,
    Month = format(month_year, "%b"),
    Year = factor(format(month_year, "%Y")),
    Month_num = as.numeric(format(month_year, "%m")),
    Establishment_Size = factor(
      Establishment_Size,
      levels = c(
        "All",
        "Large",
        "Small",
        "Very Small"
      )
    )
  )

# Plot
p_salmonella_est <- ggplot(
  prevalence_plot,
  aes(
    x = Month_Year,
    y = Percent_Positive * 100,
    color = Establishment_Size,
    group = Establishment_Size
  )
) +
  geom_line(
    linewidth = 0.8
  ) +
  geom_point(
    size = 1.8
  ) +
  labs(
    x = NULL,
    y = expression(""*italic("Salmonella")*" Positive (%)"),
    color = "Establishment Size",
    title = expression(
      "(a) "*italic("Salmonella")*
      " Positive across establishment sizes over time"
    )
  ) +
  scale_color_manual(
    values = c(
      "All" = "black",
      "Large" = "#F28E2B",
      "Small" = "#a559aa",
      "Very Small" = "#4E79A7"
    )
  ) +
  scale_x_date(
    date_breaks = "3 months",
    date_labels = "%b\n%Y",
    expand = expansion(mult = c(0.01, 0.02))
  ) +
  scale_y_continuous(
    limits = c(0, NA),
    expand = expansion(mult = c(0, 0.05))
  ) +
  theme_classic(base_size = 15) +
  theme(
    legend.position = "right",
    axis.text.x = element_text(
      angle = 0,
      hjust = 1,
      vjust = 1
    ),
    panel.grid.major.y = element_line(
      linewidth = 0.3,
      color = "grey90"
    )
  )
p_salmonella_est

combined_category_plot <- 
  p_salmonella_est / category_overtime +
  plot_layout(widths = c(1, 1),heights = c(1,3))


ggsave("figures/category_plot_byest.jpg", combined_category_plot, width = 10, height = 15)

```

```{r trend test - STable 8}
library( Kendall )
library( dplyr )

# Run Mann-Kendall test for each establishment size and category combination
mk_results <- plot_prop %>%
  group_by(establishment_size, category) %>%
  arrange(end_date) %>%
  summarise(
    tau = MannKendall(proportion)$tau[1],
    p_value = MannKendall(proportion)$sl[1],
    .groups = "drop"
  ) %>%
  mutate(
    significant = ifelse(p_value < 0.05, "Yes", "No")
  )

print(mk_results)

```


